// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: orders.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const copyCartDataIntoOrder = `-- name: CopyCartDataIntoOrder :many
INSERT INTO orders_variants (order_id, product_variant_id, quantity, price_per_item, total_price)
SELECT 
  $1, 
  cv.product_variant_id, 
  cv.quantity, 
  cv.price_per_item,
  (cv.quantity * cv.price_per_item)
FROM carts_variants cv
WHERE cv.cart_id = $2
RETURNING order_id, product_variant_id, quantity, price_per_item, total_price, created_at, updated_at
`

type CopyCartDataIntoOrderParams struct {
	OrderID uuid.UUID `json:"order_id"`
	CartID  uuid.UUID `json:"cart_id"`
}

func (q *Queries) CopyCartDataIntoOrder(ctx context.Context, arg CopyCartDataIntoOrderParams) ([]OrdersVariant, error) {
	rows, err := q.db.QueryContext(ctx, copyCartDataIntoOrder, arg.OrderID, arg.CartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrdersVariant
	for rows.Next() {
		var i OrdersVariant
		if err := rows.Scan(
			&i.OrderID,
			&i.ProductVariantID,
			&i.Quantity,
			&i.PricePerItem,
			&i.TotalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    user_id, 
    total_price, 
    customer_email, 
    shipping_name, 
    shipping_address, 
    shipping_city, 
    shipping_postal_code, 
    shipping_country, 
    shipping_phone, 
    billing_name, 
    billing_address, 
    billing_city, 
    billing_postal_code, 
    billing_country,
    shipping_option_id,
    shipping_price,
    payment_option_id
)
VALUES (
    $1, 
    $2, 
    $3, 
    $4, 
    $5, 
    $6, 
    $7, 
    $8, 
    $9, 
    $10, 
    $11, 
    $12, 
    $13, 
    $14,
    $15,
    $16,
    $17
)
RETURNING id, user_id, status, total_price, created_at, updated_at, customer_email, shipping_name, shipping_address, shipping_city, shipping_postal_code, shipping_country, shipping_phone, billing_name, billing_address, billing_city, billing_postal_code, billing_country, shipping_option_id, shipping_price, payment_option_id
`

type CreateOrderParams struct {
	UserID             uuid.NullUUID  `json:"user_id"`
	TotalPrice         float64        `json:"total_price"`
	CustomerEmail      string         `json:"customer_email"`
	ShippingName       sql.NullString `json:"shipping_name"`
	ShippingAddress    sql.NullString `json:"shipping_address"`
	ShippingCity       sql.NullString `json:"shipping_city"`
	ShippingPostalCode sql.NullString `json:"shipping_postal_code"`
	ShippingCountry    sql.NullString `json:"shipping_country"`
	ShippingPhone      string         `json:"shipping_phone"`
	BillingName        sql.NullString `json:"billing_name"`
	BillingAddress     sql.NullString `json:"billing_address"`
	BillingCity        sql.NullString `json:"billing_city"`
	BillingPostalCode  sql.NullString `json:"billing_postal_code"`
	BillingCountry     sql.NullString `json:"billing_country"`
	ShippingOptionID   uuid.NullUUID  `json:"shipping_option_id"`
	ShippingPrice      float64        `json:"shipping_price"`
	PaymentOptionID    uuid.NullUUID  `json:"payment_option_id"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.UserID,
		arg.TotalPrice,
		arg.CustomerEmail,
		arg.ShippingName,
		arg.ShippingAddress,
		arg.ShippingCity,
		arg.ShippingPostalCode,
		arg.ShippingCountry,
		arg.ShippingPhone,
		arg.BillingName,
		arg.BillingAddress,
		arg.BillingCity,
		arg.BillingPostalCode,
		arg.BillingCountry,
		arg.ShippingOptionID,
		arg.ShippingPrice,
		arg.PaymentOptionID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerEmail,
		&i.ShippingName,
		&i.ShippingAddress,
		&i.ShippingCity,
		&i.ShippingPostalCode,
		&i.ShippingCountry,
		&i.ShippingPhone,
		&i.BillingName,
		&i.BillingAddress,
		&i.BillingCity,
		&i.BillingPostalCode,
		&i.BillingCountry,
		&i.ShippingOptionID,
		&i.ShippingPrice,
		&i.PaymentOptionID,
	)
	return i, err
}

const getOrderById = `-- name: GetOrderById :one
SELECT id, user_id, status, total_price, created_at, updated_at, customer_email, shipping_name, shipping_address, shipping_city, shipping_postal_code, shipping_country, shipping_phone, billing_name, billing_address, billing_city, billing_postal_code, billing_country, shipping_option_id, shipping_price, payment_option_id FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderById(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderById, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerEmail,
		&i.ShippingName,
		&i.ShippingAddress,
		&i.ShippingCity,
		&i.ShippingPostalCode,
		&i.ShippingCountry,
		&i.ShippingPhone,
		&i.BillingName,
		&i.BillingAddress,
		&i.BillingCity,
		&i.BillingPostalCode,
		&i.BillingCountry,
		&i.ShippingOptionID,
		&i.ShippingPrice,
		&i.PaymentOptionID,
	)
	return i, err
}

const getOrderItemsByOrderId = `-- name: GetOrderItemsByOrderId :many
SELECT order_id, product_variant_id, quantity, price_per_item, total_price, created_at, updated_at FROM orders_variants
WHERE order_id = $1
`

func (q *Queries) GetOrderItemsByOrderId(ctx context.Context, orderID uuid.UUID) ([]OrdersVariant, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItemsByOrderId, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrdersVariant
	for rows.Next() {
		var i OrdersVariant
		if err := rows.Scan(
			&i.OrderID,
			&i.ProductVariantID,
			&i.Quantity,
			&i.PricePerItem,
			&i.TotalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrders = `-- name: GetOrders :many
SELECT id, user_id, status, total_price, created_at, updated_at, customer_email, shipping_name, shipping_address, shipping_city, shipping_postal_code, shipping_country, shipping_phone, billing_name, billing_address, billing_city, billing_postal_code, billing_country, shipping_option_id, shipping_price, payment_option_id FROM orders
ORDER BY created_at DESC
`

func (q *Queries) GetOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.TotalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerEmail,
			&i.ShippingName,
			&i.ShippingAddress,
			&i.ShippingCity,
			&i.ShippingPostalCode,
			&i.ShippingCountry,
			&i.ShippingPhone,
			&i.BillingName,
			&i.BillingAddress,
			&i.BillingCity,
			&i.BillingPostalCode,
			&i.BillingCountry,
			&i.ShippingOptionID,
			&i.ShippingPrice,
			&i.PaymentOptionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByOwnerUserId = `-- name: GetOrdersByOwnerUserId :many
SELECT id, user_id, status, total_price, created_at, updated_at, customer_email, shipping_name, shipping_address, shipping_city, shipping_postal_code, shipping_country, shipping_phone, billing_name, billing_address, billing_city, billing_postal_code, billing_country, shipping_option_id, shipping_price, payment_option_id FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetOrdersByOwnerUserId(ctx context.Context, userID uuid.NullUUID) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getOrdersByOwnerUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.TotalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerEmail,
			&i.ShippingName,
			&i.ShippingAddress,
			&i.ShippingCity,
			&i.ShippingPostalCode,
			&i.ShippingCountry,
			&i.ShippingPhone,
			&i.BillingName,
			&i.BillingAddress,
			&i.BillingCity,
			&i.BillingPostalCode,
			&i.BillingCountry,
			&i.ShippingOptionID,
			&i.ShippingPrice,
			&i.PaymentOptionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByStatus = `-- name: GetOrdersByStatus :many
SELECT id, user_id, status, total_price, created_at, updated_at, customer_email, shipping_name, shipping_address, shipping_city, shipping_postal_code, shipping_country, shipping_phone, billing_name, billing_address, billing_city, billing_postal_code, billing_country, shipping_option_id, shipping_price, payment_option_id FROM orders
WHERE status IN ($1)
ORDER BY created_at DESC
`

func (q *Queries) GetOrdersByStatus(ctx context.Context, status OrderStatus) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getOrdersByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.TotalPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerEmail,
			&i.ShippingName,
			&i.ShippingAddress,
			&i.ShippingCity,
			&i.ShippingPostalCode,
			&i.ShippingCountry,
			&i.ShippingPhone,
			&i.BillingName,
			&i.BillingAddress,
			&i.BillingCity,
			&i.BillingPostalCode,
			&i.BillingCountry,
			&i.ShippingOptionID,
			&i.ShippingPrice,
			&i.PaymentOptionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $1
WHERE id = $2
RETURNING id, user_id, status, total_price, created_at, updated_at, customer_email, shipping_name, shipping_address, shipping_city, shipping_postal_code, shipping_country, shipping_phone, billing_name, billing_address, billing_city, billing_postal_code, billing_country, shipping_option_id, shipping_price, payment_option_id
`

type UpdateOrderStatusParams struct {
	Status OrderStatus `json:"status"`
	ID     uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrderStatus, arg.Status, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerEmail,
		&i.ShippingName,
		&i.ShippingAddress,
		&i.ShippingCity,
		&i.ShippingPostalCode,
		&i.ShippingCountry,
		&i.ShippingPhone,
		&i.BillingName,
		&i.BillingAddress,
		&i.BillingCity,
		&i.BillingPostalCode,
		&i.BillingCountry,
		&i.ShippingOptionID,
		&i.ShippingPrice,
		&i.PaymentOptionID,
	)
	return i, err
}
